formatter: markdown table

recursive:
  enabled: false
  path: environments/modules
  include-main: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs
    - resources

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: false
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
