"""create deployments table

Revision ID: 322374a72d98
Revises: 
Create Date: 2026-04-27 14:52:35.659918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322374a72d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_name', 'version', 'environment', name='uq_deployment_app_version_environment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    # ### end Alembic commands ###
